/**
 * @type {import('./types').Deployment[]}
 */
export const mockDeployments = [
  {
    id: '1',
    title: 'v2.3.1 배포',
    service: 'Auth Service',
    branch: 'feature/auth',
    prTitle: 'feat: OAuth 2.0 구현',
    status: 'scheduled',
    date: '2025-10-20',
    scheduledTime: '14:00',
    riskLevel: '중',
    prNumber: '#124',
  },
  {
    id: '2',
    title: 'v3.0.0 배포',
    service: 'API Gateway',
    branch: 'main',
    prTitle: 'feat: 대시보드 리디자인',
    status: 'success',
    date: '2025-10-10',
    scheduledTime: '10:30',
    riskLevel: '상',
    prNumber: '#142',
  },
  {
    id: '3',
    title: 'Hotfix 배포',
    service: '결제 서비스',
    branch: 'hotfix/payment-bug',
    prTitle: 'fix: 결제 오류 수정',
    status: 'failed',
    date: '2025-10-12',
    scheduledTime: '16:45',
    riskLevel: '하',
    prNumber: '#156',
  },
  {
    id: '4',
    title: 'v2.4.0 배포',
    service: '공지 서비스',
    branch: 'feature/notifications',
    prTitle: 'feat: 실시간 알림 추가',
    status: 'scheduled',
    date: '2025-10-25',
    scheduledTime: '11:00',
    riskLevel: '중',
    prNumber: '#167',
  },
  {
    id: '5',
    title: 'v1.9.2 배포',
    service: '인사 서비스',
    branch: 'release/1.9.2',
    prTitle: 'feat: 사용자 프로필 개선',
    status: 'success',
    date: '2025-10-14',
    scheduledTime: '09:00',
    riskLevel: '하',
    prNumber: '#189',
  },
  {
    id: '6',
    title: 'v4.1.0 배포',
    service: 'AI 서비스',
    branch: 'feature/analytics',
    prTitle: 'feat: 분석 대시보드',
    status: 'scheduled',
    date: '2025-10-28',
    scheduledTime: '15:30',
    riskLevel: '상',
    prNumber: '#201',
  },
  {
    id: '7',
    title: 'v2.2.0 배포',
    service: 'Auth Service',
    branch: 'release/2.2.0',
    prTitle: 'feat: 2FA 인증 추가',
    status: 'success',
    date: '2025-10-08',
    scheduledTime: '15:00',
    riskLevel: '중',
    prNumber: '#130',
  },
  {
    id: '8',
    title: '긴급 패치',
    service: '결제 서비스',
    branch: 'hotfix/security',
    prTitle: 'fix: 보안 취약점 수정',
    status: 'failed',
    date: '2025-10-09',
    scheduledTime: '22:30',
    riskLevel: '상',
    prNumber: '#138',
  },
  {
    id: '9',
    title: 'v3.2.0 배포',
    service: '검색 서비스',
    branch: 'feature/search-v3',
    prTitle: 'feat: 고급 검색 기능',
    status: 'scheduled',
    date: '2025-10-20',
    scheduledTime: '16:30',
    riskLevel: '중',
    prNumber: '#215',
  },
];

/**
 * @type {import('./types').RestrictedPeriod[]}
 */
export const mockRestrictedPeriods = [
  {
    id: 'r1',
    title: '정기 점검',
    description: '시스템 전체 정기 점검 작업',
    startDate: '2025-10-23',
    startTime: '00:00',
    endDate: '2025-10-24',
    endTime: '06:00',
    type: '서버 점검',
  },
  {
    id: 'r2',
    title: 'DB 마이그레이션',
    description: '데이터베이스 스키마 업데이트',
    startDate: '2025-10-26',
    startTime: '22:00',
    endDate: '2025-10-27',
    endTime: '02:00',
    type: 'DB 마이그레이션',
  },
  {
    id: 'r3',
    title: '긴급 보안 패치',
    description: '보안 취약점 긴급 패치 작업',
    startDate: '2025-10-15',
    startTime: '14:00',
    endDate: '2025-10-17',
    endTime: '18:00',
    type: '외부 일정',
  },
];
